namespace RecipeManagementSystem.Models.Db
{
    public class RecipeStep
    {
        public int? Id { get; set; }
        public int? RecipeId { get; set; }
        public string Description { get; set; }
        public int OrderIdx { get; set; } //todo place a autogenerated value, based on how much steps is present in the recipe

        public Recipe Recipe { get; set; }
    }
}